### ISSUE TITLE
Cant add reactions with >py command

### ISSUE THREAD

**Issue by copycat114** [appu1232/Discord-Selfbot#10]
I can't seem to get a custom )py command to work
`)py bot.add_reaction(discord.Message(id='300425969653514240'), ':ok_hand:')` 
i get an error in the command prompt along the lines of  
 `UnicodeEncodeError: 'charmap' codec can't encode character '\u2139' in position 143: character maps to <undefined>`

**Comment by appu1232** [comment]
This is more of a discord.py questions rather than a question for the selfbot. I beilieve the syntax is wrong anyway. ``add_reaction`` is a coroutine so it needs to be called by using ``await``
