### ISSUE TITLE
is there an afk feature

### ISSUE THREAD

**Issue by DamonOnYT** [appu1232/Discord-Selfbot#101]
if there a feature where if someone mentions me it says I'm afk and i can set a reason?

**Comment by appu1232** [comment]
No, selfbots are not allowed to respond to others

**Comment by DamonOnYT** [comment]
aww

**Comment by DamonOnYT** [comment]
I've seen other selfbots do that but idk what their called

**Comment by appu1232** [comment]
If they do, they are breaking Discord ToS.
