### ISSUE TITLE
Embed doesn't work (for me)

### ISSUE THREAD

**Issue by Hubcapp** [appu1232/Discord-Selfbot#11]
I blame 014c9427d81e5853486476ef1dd573d928c63549

Embedding worked before updating from an old version.

I get this error now:
From line 107 of misc.py: `AttributeError: module 'discord' has no attribute 'Embed'`

Old code (worked for me):
`em = discord.Embed(description=msg)`

New code (raises an exception, embeds don't work):
`em = discord.Embed(title=title, description=description, color=int(color, 16))`

-----

My version of the discord library is
`Requirement already satisfied: discord.py==0.16.6 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))`

My operating system is Debian.

**Comment by Hubcapp** [comment]
Could be something else, I just remember that it worked before and now it doesn't and that's the last time I saw that line changed.

**Comment by appu1232** [comment]
Fixed (sort of) the problem on Discord. Seems to be a problem with Mac/Linux invalid permissions when running the script/bot without ``sudo``. Will see if there's a workaround but for now, ``sudo bash run_linuxmac.sh`` seems like the best solution.
