### ISSUE TITLE
the image command

### ISSUE THREAD

**Issue by Q-u-i-l-l** [appu1232/Discord-Selfbot#13]
when using the [prefix]i [query]

it doesnt delete the command after execution.
please fix it :)

**Comment by appu1232** [comment]
Yea, I have it set to delete the command for some but for others i thought it might be helpful to know what command was used. I was thinking about setting the image command to delete since it's not all that needed. Will do this for the next update.

**Comment by Q-u-i-l-l** [comment]
Thanks :)

Love having active developers working on something and updating every now
and then. Love yall!!
