### ISSUE TITLE
Don't force me to use one letter prefixes.

### ISSUE THREAD

**Issue by LittleEndu** [appu1232/Discord-Selfbot#14]
I just spent 15 minutes fixing this.
https://github.com/appu1232/Discord-Selfbot/blob/master/appuselfbot.py#L25

remove that [0] please

**Comment by appu1232** [comment]
I used a lot of code that depends on splitting messages based on the length of the command. In hindsight it was bad but back then I wasn't planning on releasing the bot to the public so I wasn't too worried. There's some other code too that depends on this in the other cogs so I'd have to go through and fix it for all of them. Will do it eventually.

**Comment by appu1232** [comment]
Added support for this in the latest update.
