### ISSUE TITLE
Avatar command not working

### ISSUE THREAD

**Issue by Hoppit** [appu1232/Discord-Selfbot#142]
Hello there! One of my friends uses your self bot, and she was trying to get the avatar rotation command to work. When she claimed that it was not working I decided to look into it for her. But whenever the bot attempted to change her avatar I got this error;
![image](https://user-images.githubusercontent.com/29414775/28990042-84859c50-792e-11e7-9fec-c461bc2c158a.png)
(this picture is actually the second trial, but both errors where the same.)
I tried reinstalling a new version of the bot and running it on another account, but I got the same error. The password was correct on both trials, and I tried all three of these times for the delay (in seconds); 1800, 2000, 7250. And the self bot is fully updated.
I have not gone and edited the named file location because I am not that great with programming yet. 
Would someone tell me what I need to change/edit in order to get this commands working? Thanks in advance!

**Comment by Hoppit** [comment]
I decided in my copy of the bot I will try removing this bit of code; , `encoding="utf8"`. If there are any other recommendations or ideas please notify me immediately.

**Comment by appu1232** [comment]
It seems that this is an issue with an update to avatar that was pushing recently. I'll revert it and push it soon.

**Comment by appu1232** [comment]
Oops, didn't mean to do that. Anyway, fixed it here: https://github.com/appu1232/Discord-Selfbot/commit/be51355dea8c29cb4cc5231a4e9ec1ed6c76516c

Should be all set now.

**Comment by Hoppit** [comment]
Thank you, sorry to bother you
