### ISSUE TITLE
Bot has started to hang on "starting bot"

### ISSUE THREAD

**Issue by Tehmaxx** [appu1232/Discord-Selfbot#153]
Bot was working fine for about a month, but now it just hangs on starting.

Tried to start from scratch and it takes you through all the steps again and hangs forever at "starting bot"

**Comment by appu1232** [comment]
Known problem when your internet connection isn't all that great. It will take a while for it to log in. You'll have to either live with it or possibly try on a different connection. It can't really be fixed from my end.
