### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ereenn** [appu1232/Discord-Selfbot#156]
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

**Comment by appu1232** [comment]
Not sure where this error is appearing but it doesn't seem to have to do with the bot or its dependencies. I would suggest reinstalling Python. Make sure you add to PATH when reinstalling.
