### ISSUE TITLE
Updated code wont work

### ISSUE THREAD

**Issue by DevilTentacion** [appu1232/Discord-Selfbot#161]
You updated the code and now it isnt working for anyone.

**Comment by shikhir-arora** [comment]
Need more details than that; please elaborate. The bot is [tested upon each push](https://travis-ci.org/appu1232/Discord-Selfbot/jobs/261657597) and compiles fine.

**Comment by DevilTentacion** [comment]
It says that Python isnt installed to PATH when it is, has imgur link that shows enable PATH. My friend who uses the same bot updated the bot and now the commands wont work for him, for me it doesnt even work.

**Comment by appu1232** [comment]
If there's a `settings2` folder in the bot directory, rename it to `settings`.

Also, one up a command prompt window and type `python -V` (that's a capital V). Post what it returns.

**Comment by appu1232** [comment]
Assuming there isn't a response because the matter is resolved so I will be closing this. Re-open if you are still having issues or visit the server or better one-on-one help.
