### ISSUE TITLE
(Feature Request) Able to download cog from a external link

### ISSUE THREAD

**Issue by pokecraft98** [appu1232/Discord-Selfbot#165]
Example "cog download https://github.com/PhazonicRidley/Assistance-Links/raw/master/assistance_links.py"

**Comment by appu1232** [comment]
You are already able to install custom cogs via the `>cog install` command which can install any of the cogs listed here: https://github.com/LyricLy/ASCII/tree/master/cogs (also viewable via `>cog list`). However, the selfbot isn't just going to work with any cog and therefore I don't want to add a feature that lets people download cogs that may not be supported. For now if there is a cog that is supported, the author may submit it to cogs list and if approved, it will appear for in the `>cog list` for anyone to download.

**Comment by LyricLy** [comment]
The ASCII was created specifically to circumvent the issue of being able to link malicious cogs to users without their knowledge. I already had this feature implemented (i vaguely remember giving it to you earlier) but I was worried about how it could be used, so I created ASCII.

**Comment by pokecraft98** [comment]
okay i understand
