### ISSUE TITLE
[Suggestion] Online Status Blinker

### ISSUE THREAD

**Issue by Untuned** [appu1232/Discord-Selfbot#176]
This idea came from another user who had this.

The command would be something like >blinker, where you can give 2-3 options.  Online, DnD, or Away.
Every couple of seconds, it will swap your online status between what options you have set.  (I'd rather not see people blinking online/offline, therefore Invisible should be disabled.

**Comment by Dunciboy** [comment]
That's not what statuses ar meant to be used for and I doubt discord would like you being rate limited from changing your status every 1 second.
