### ISSUE TITLE
Imprecise permission listing in channelinfo

### ISSUE THREAD

**Issue by chenzw95** [appu1232/Discord-Selfbot#179]
Currently, `channelinfo` checks for the presence of an explicit allow permission to "Read messages" in order to determine whether a specific role/user is considered an "Allowed role".

This can lead to a false positive for "Restricted roles" if permission overrides are defined for a role, but the "Read messages" permission is not overriden (set to neutral, `PermissionOverwrite is None`).

**Comment by LyricLy** [comment]
Addressed in 57c2be5.
