### ISSUE TITLE
24-hour time option for time commands

### ISSUE THREAD

**Issue by NootNootEh** [appu1232/Discord-Selfbot#180]
Idk where to post/ask for this, so I thought why not here, could we get the ability to not use "Military" time when you use the command to check the time, possibility of using 12 hour clock or 24

**Comment by GriffinG1** [comment]
It's already planned

**Comment by NootNootEh** [comment]
Wow that was fast, thanks for the response and good to know ^.^

**Comment by chenzw95** [comment]
Reopening to keep track of this issue request.

**Comment by architdate** [comment]
I'll submit a PR for this soon

**Comment by architdate** [comment]
then merge when it's ready

**Comment by JakerX** [comment]
Ok

**Comment by Macley-Kun** [comment]
Isn't this already in the bot? Correct me if i'm wrong.
