### ISSUE TITLE
Linux Ubuntu 16.04 Spam

### ISSUE THREAD

**Issue by Ecxdirerr** [appu1232/Discord-Selfbot#184]
http://toast-for.life/icrka.png
The bot spams this constantly.
Whats the problem with it?

**Comment by architdate** [comment]
This is not a place to ask setup help. It is to report actual Issues. Your discord is not updated to `v 1.0.0` (post rewrite).  To fix this just update your discord to the latest rewrite build from either pip or using git with `@rewrite`. If you need further assistance on the matter, please as on the discord chat.
