### ISSUE TITLE
Is it possible to use in DM's?

### ISSUE THREAD

**Issue by IkkixD** [appu1232/Discord-Selfbot#190]
I mainly use discords calling feature(screenshare) when talking to friends. Is it possible to use this selfbot in DM's?

**Comment by LyricLy** [comment]
It depends on what commands you are planning to use. Many of the commands do work in DMs, but keep in mind that some of them may function abnormally or fail to work at all.

**Comment by IkkixD** [comment]
The main use would be google/image search and My anime list search. How would I get it to respond in DM's?

**Comment by IkkixD** [comment]
Hmm, commands didn't go through when I tried yesterday, but they work now. Thanks lol.

**Comment by IkkixD** [comment]
These commands work in my DM's for 1 of my friends, but none of my other friends?
