### ISSUE TITLE
[Suggestion] Rich Presence? 

### ISSUE THREAD

**Issue by NootNootEh** [appu1232/Discord-Selfbot#193]
Don't know where else to put this tbh so I thought I'd put it here, possible to get the Ability to modify and or use Rich Presence?

**Comment by Hexexpeck** [comment]
i would say using rich presence is against the api terms but by using a selfbot you're abusing the api anyways /shrug

**Comment by Hexexpeck** [comment]
besides, the discord.py rewrite doesn't implement rich presence yet iirc, unless you know which HTTP requests to send/receive if you want rich presence

**Comment by JoshuaBishop** [comment]
Rich Presences are against ToS right now.... So I wouldn't suggest that yet. At least not until it's fully rolled out
