### ISSUE TITLE
Question: Where is the help command located?

### ISSUE THREAD

**Issue by TheRoyalBlock** [appu1232/Discord-Selfbot#204]
I am an experienced programmer, I just don't know python. I understand algorithms and variables and that type of thing, feel free to talk about that in the answer. How do you format the help command to get the end result? I could not find anything talking about like 
When user types <prefix>help, output <commandname> ᅠᅠᅠ<description>

Would you mind pointing this out to me? I hope to use a similar technique in one of my future projects (and at the moment I want to edit the bot and make my own help command)

THANKS!

**Comment by appu1232** [comment]
The help command is generated by discord.py. It takes all the registered commands and parses the docstring for each command under the function definition as the help output. Here is the [Helpformatter class](https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/formatter.py#L126-L346) for discord.py rewrite.

**Comment by TheRoyalBlock** [comment]
Thanks for the fast reply! How would I be able to cancel the help command request and replace it with my own? Would I have to modify discord.py?

**Comment by LyricLy** [comment]
You would have to override the HelpFormatter class.

**Comment by TheRoyalBlock** [comment]
Lol that's more work than I expected to do
