### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by Kawaiikat14** [appu1232/Discord-Selfbot#213]
Failed to transfer custom cogs to custom_cogs folder. Error: HTTPConnectionPool(host='appucogs.tk', port=80): Max retries exceeded with url: /cogs/notforth.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0501DDD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by architdate** [comment]
should just be bad connectivity on your side. the website does give a response to a GET request

**Comment by astronautlevel2** [comment]
Closing as OP hasn't responded.
