### ISSUE TITLE
Exception from g command

### ISSUE THREAD

**Issue by beboobailey** [appu1232/Discord-Selfbot#223]
I get the following error when running the `g` command. I have set the api key and cse key as required and the image search works, just not google searching.

```------
Ignoring exception in command g
Traceback (most recent call last):
  File "/home/miner/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/miner/SelfBot2/cogs/google.py", line 171, in g
    if len(entries) == 0:
TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miner/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/miner/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/miner/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object of type 'NoneType' has no len()```

**Comment by chenzw95** [comment]
Can you tell us your search query?

**Comment by beboobailey** [comment]
Doesn’t matter the search query. I tried several such as “test” “toast”
“YouTube” and other obvious words that produce results with regular discord
bots that also use the same api key and cse key. All without quotes, of
course.

**Comment by NewbieH4x** [comment]
works fine for me, no such issue.

**Comment by beboobailey** [comment]
Ok, doing some digging. Looks like the problem is in `cogs/util/checks.py` for `get_google_entries()`. I echoed the output of resp from line [172](https://github.com/appu1232/Discord-Selfbot/blob/d3648270e20ccdd5ac3d7eacba3dc17965ff9f55/cogs/utils/checks.py#L172) and got a 503 error. 

`<ClientResponse(https://ipv6.google.com/sorry/index?continue=https://www.google.com/search?q%3Dtest%26safe%3Doff%26lr%3Dlang_en%26h1%3Den&q=EhAmADwDAAAAAPA8kf_-cHtbGJqHmM8FIhkA8aeDSzfxkde8OusZ4gyMaLeZUl8meizOMgFy) [503 Service Unavailable]>`

Looks like it might be IPv6 related?

**Comment by appu1232** [comment]
Ah, this has happened before. Basically, I have the same Google search method as Danny's RoboDanny but fall back on the API key if Google blocks that call. Looks like Google blocked that call for you but it doesn't seem to fall back on the API key and custom search id method. Do you have those set up?

**Comment by beboobailey** [comment]
I do have them set. I am using them in a custom [public] bot I am writing and they work fine.

**Comment by beboobailey** [comment]
I disabled IPv6 on the server it is running on and it is working now.
