### ISSUE TITLE
>hackban didn't get added to the >ban command yet

### ISSUE THREAD

**Issue by Ulexos** [appu1232/Discord-Selfbot#234]
it only got removed entirely instead:

https://github.com/appu1232/Discord-Selfbot/commit/09670653bed7fba20da5b8ccf3e25ebdf0ab53f8#diff-b74197c8f57594715748f000a512c127L48

**Comment by Garcia1008** [comment]
Could you add hackban back please?

**Comment by appu1232** [comment]
I'll add it in tomorrow.

**Comment by Garcia1008** [comment]
thanks

**Comment by Garcia1008** [comment]
👀

**Comment by Ulexos** [comment]
@Garcia1008 it's already been added back in(to?) the dev branch 👀

**Comment by chenzw95** [comment]
Fixed in 49e39bb.
