### ISSUE TITLE
[Not An Issue] Is there a way I can add custom coded commands ?

### ISSUE THREAD

**Issue by KshitijSharmaIsCoding** [appu1232/Discord-Selfbot#240]
Just like the title says I want to add a command that sends a message every one minute. I have the code ready if you could be so kind to point me to where I can add it so it will become its own command ?

**Comment by appu1232** [comment]
> I want to add a command that sends a message every one minute.

This can already be done with the `todo` command, although I wouldn't recommend such a potentially spammy task.

If you are still looking to creating your own command, look into creating cogs. All the cogs in the cogs folder are examples of commands that are basically added onto the bot.
