### ISSUE TITLE
WebSocket connection

### ISSUE THREAD

**Issue by FaireSkD** [appu1232/Discord-Selfbot#243]
Continuing logging in...
Logged in as
Faire
User id:299733047346069505
------
Something went wrong: WebSocket connection is closed: no code, no reason.
Something went wrong: WebSocket connection is closed: no code, no reason.
Logged in as
Faire
User id:299733047346069505
------
Something went wrong: WebSocket connection is closed: no code, no reason.

**Comment by appu1232** [comment]
The connection was closed, probably due to inconsistent internet or some issue with the connection. There really isn't a reason or a fix I can give you, just like the log says. Best you can do is just try again and maybe try with a different internet connection.
