### ISSUE TITLE
Error running on VPS (Ubuntu Server 16.04)

### ISSUE THREAD

**Issue by SlimShadyIAm** [appu1232/Discord-Selfbot#248]
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...

This continues to loop. I made sure all the requirements are installed. I had no issues getting it to run on a home server.

**Comment by astronautlevel2** [comment]
Okay, I think I see what's causing this. I'll look more into it when I get home.

**Comment by SlimShadyIAm** [comment]
@astronautlevel2 you home yet? :D

**Comment by Macley-Kun** [comment]
![image](https://user-images.githubusercontent.com/26381427/34327570-055d4c7a-e8c8-11e7-9cd2-d23c031a002e.png)

**Comment by shivaco** [comment]
My bet is on wrong config.json setup.

**Comment by Macley-Kun** [comment]
We'll see :^)

**Comment by how-do-i-code-help-me-help-hello** [comment]
Having same issue on Ubuntu 17.10 x64

**Comment by how-do-i-code-help-me-help-hello** [comment]
@shivaco any examples? should be easy to replicate if so

**Comment by SlimShadyIAm** [comment]
Actually no, I used the same config I used on the VPS on my local server;
it worked on the local server and didn't on the VPS.

**Comment by EliteDaMyth** [comment]
The issue is not with the bot its just that you are running the thing as sudo or from the root user

**Comment by shivaco** [comment]
I ran it from the root user and it was working for me. 🤔

**Comment by SlimShadyIAm** [comment]
Wow this issue is still going?

Same, I ran it from root on a different machine without issue.

**Comment by chenzw95** [comment]
Is this still an issue?

**Comment by chenzw95** [comment]
No updates, closing.
