### ISSUE TITLE
Syntax error while running run_linuxmac.sh

### ISSUE THREAD

**Issue by itsnaeng** [appu1232/Discord-Selfbot#249]
I'm on Ubuntu 14.04.5 LTS, when running the run_linuxmac.sh I get this error:
```
SyntaxError: invalid syntax
  File "appuselfbot.py", line 199
    async def on_ready():
        ^
```

I have python2 as default with python3 installed:
```
naeng@naeng:~/selfbot# python --version
Python 2.7.6
naeng@naeng:~/selfbot# python3 --version
Python 3.5.3
```

How can I fix this?

**Comment by astronautlevel2** [comment]
This isn't a troubleshooting forum; please ask in the #help channel in https://discord.gg/TBQE72k
