### ISSUE TITLE
display at startup is spread

### ISSUE THREAD

**Issue by clragon** [appu1232/Discord-Selfbot#250]
The message displayed on startup is not a function but copy and pasted in all files that use it. 
I would rather have it a function so it can be adjusted easier.

**Comment by LyricLy** [comment]
I don't see a reason to change this. The message is only in two files and it's barely used in one of them.

**Comment by clragon** [comment]
Okay so I just edited it for some small adjustments like putting username and ID in another place but I can imagine it would be useful for people who want to print more informations on it, customize it in any way etc.

I was thinking about just letting clear call the function the code was originally used in but that would trigger more complex things that shouldnt be used in clear. 

![screenshot_1](https://user-images.githubusercontent.com/11785085/33287143-041eb756-d3b8-11e7-9a98-c75a017fa821.png)

This is what I edited. /shrug
