### ISSUE TITLE
aiohttp failing to install with requiring Python 3.4.2+ but I have Python 3.5.2

### ISSUE THREAD

**Issue by Drakonas** [appu1232/Discord-Selfbot#254]
I apologize if this is something on my system, but I can't figure out why aiohttp is not wanting to install. Is there a newer version that is not in the repo anymore?

It says at the beginning of the installs that it is using the global pip3 executable. I am not running as root.

Ubuntu's Python implementation is stupid. Lol.

![screenshot](http://genesis.whatbox.ca:42424/img/kitty_2017-11-25_22-07-47.png)

**Comment by SlimShadyIAm** [comment]
If you were to run `python --version` it would give you a different version. That's the version Ubuntu defaults to. 

To get around this, try running `pip3 install -r requirements.txt` and then running the bot.

**Comment by LyricLy** [comment]
@SlimShadyIAm Your statement is not entirely true. The bot uses Python 3 by default.

**Comment by Drakonas** [comment]
@SlimShadyIAm yeah, if you had read my OP, it said that the script put out a line that said "using global pip3 executable", so it should be using Python 3. Looking in the script code, it is supposed to detect Python or Python 3 and use the proper executable.

**Comment by astronautlevel2** [comment]
This is not a troubleshooting forum - please ask your question in #help on the discord.

**Comment by Drakonas** [comment]
@astronautlevel2 Thanks for looking over my bug. It was not troubleshooting. The script is not properly using pip3 on my system.

The correct command to be used is "sudo -H python3 -m pip install [package]". The script is using "pip3 install [package]" which will not work on some distros or some setups. "python3 -m pip" explicitly invokes Python3's pip.

**Comment by chenzw95** [comment]
`pip3` pointing to the pip for python 2.7 is a misconfiguration. Please reinstall the python3 pip package using your distro's package manager.

**Comment by Drakonas** [comment]
@chenzw95 I have purged and done that already. Still points to Python2. The fact stands that python3 -m pip exclusively runs python3's pip, whereas running pip3 directly relies on pip3 executeable pointing the right pip version.

**Comment by Drakonas** [comment]
@chenzw95 thank you for being willing to fix though. Really appreciate it.
