### ISSUE TITLE
[macOS] Error on startup

### ISSUE THREAD

**Issue by Veeuroxx** [appu1232/Discord-Selfbot#263]
I am having issues while installing the bot on my machine. Here is a screenshot of the terminal:

![Screen Shot](https://user-images.githubusercontent.com/32760644/33432000-54b8b3c8-d611-11e7-95dc-8843565e1062.png)

**Comment by astronautlevel2** [comment]
Can you post the full traceback?

**Comment by chenzw95** [comment]
One week passed without any response, closing as invalid.
