### ISSUE TITLE
editembed author

### ISSUE THREAD

**Issue by FELITH** [appu1232/Discord-Selfbot#264]
Why
`author=name=Archetype icon=http://mentalomega.com/images/buttonsoviets.png url=http://moapyr.wikia.com/wiki/Archetype`
result this:
![image](https://user-images.githubusercontent.com/19184069/33434257-58b41e2c-d611-11e7-82c8-ddda34c2165a.png)

`author=name=Archetype icon=http://mentalomega.com/images/buttonsoviets.png `
result this:
![image](https://user-images.githubusercontent.com/19184069/33435433-bf08e54c-d614-11e7-8c06-d861477c7eb6.png)

**Comment by FELITH** [comment]
also 
`>embed author=Archetype icon=https://vignette.wikia.nocookie.net/moapyr/images/0/0b/Sovicon.png/revision/latest?cb=20170106162603 url=http://moapyr.wikia.com/wiki/Archetype`
result this:
![image](https://user-images.githubusercontent.com/19184069/33435268-4facd410-d614-11e7-9ad8-4400e491c6f4.png)

**Comment by FELITH** [comment]
can you add a command that removes embed from messageID.

**Comment by chenzw95** [comment]
This may have been addressed in 2833a4c. Please update and report back.

**Comment by FELITH** [comment]
yes, It's working now. thank you guys.
