### ISSUE TITLE
Emoji command crashing the bot

### ISSUE THREAD

**Issue by lbdBG** [appu1232/Discord-Selfbot#266]
# Automatically crashes after I use the Emoji command
For some reason it does that. Also when the bot is booted up it takes a long while for the python interpreter to respond to a command
Tried removing all the files and re-downloading it but it did nothing.

**Comment by chenzw95** [comment]
Please give us the traceback - we cannot troubleshoot any crash without the message from the console.

**Comment by chenzw95** [comment]
More than 3 weeks passed without response, closing. Please update the bot to the latest version to see if your issue had been solved in the meantime.
