### ISSUE TITLE
Cannot make a custom command issue another command

### ISSUE THREAD

**Issue by bmintz** [appu1232/Discord-Selfbot#267]
I'm trying to add a custom command that, when someone says "star this", does this:
\>react :star_and_crescent::star_of_david::dizzy::stars::night_with_stars::six_pointed_star::star2::eight_pointed_black_star:

However, when I try to, and run `>>star`, all of the emoji it was supposed to _react_ with were just sent as a message instead.

**Comment by chenzw95** [comment]
This appears to have been addressed on the discord server already; if there are more issues regarding this, please choose one platform (Discord or GitHub), and we will work on this from there.

It is much more effective if the conversation stays on one platform.

**Comment by bmintz** [comment]
For reference, the solution was `>add "star" ">react 💫🌠🌃🌟✴☪✡🔯"`
