### ISSUE TITLE
Getting duplicated command results.

### ISSUE THREAD

**Issue by GaIahad** [appu1232/Discord-Selfbot#278]
![appubotbug](https://user-images.githubusercontent.com/33210451/34865856-4245141e-f7b5-11e7-8167-c3ddcf42f04e.PNG)

Keep getting two results when executing a command. Any suggestions? :]

**Comment by shikhir-arora** [comment]
What OS? On Linux and macOS you can type: 

`sudo ps aux | grep appu` and if you see two running instances of `appuselfbot.py` use the `KILL -9 <ID>` to kill one of them, so if the process ID is 123: `KILL -9 123`

**Comment by chenzw95** [comment]
This is not a bug, and is due to user error, as per above and Discord.
