### ISSUE TITLE
More environment variables

### ISSUE THREAD

**Issue by Bluscream** [appu1232/Discord-Selfbot#279]
I'd like to request to be able to set all these environment variables in order to be safer when pulling from a github fork for example.

![](https://i.imgur.com/HPu6Jp8.png)

**Comment by chenzw95** [comment]
Please ask fork authors to update their repository's `.gitignore` file. Existing configuration files should no longer be overwritten by repo contents.

**Comment by Bluscream** [comment]
It's not about not overwriting anything, more about not exposing your tokens everywhere ;)

**Comment by Jan200101** [comment]
If people are going to upload their appu instance with their token to github its their fault
they should not be using github as a cloud anyways
