### ISSUE TITLE
When is the Plugin coming out?

### ISSUE THREAD

**Issue by TWILIGHTLAWZ** [appu1232/Discord-Selfbot#284]
When is the Plugin coming out?

**Comment by TWILIGHTLAWZ** [comment]
**DICK**

**Comment by astronautlevel2** [comment]
![image](https://user-images.githubusercontent.com/7305572/36811656-8ebcd802-1c9c-11e8-95c9-d4b7096574f1.png)
I'd ask you not to post things like this on our issue tracker, because even if you delete them we still end up seeing it.

What "plugin" are you even referring to?

**Comment by Bluscream** [comment]
Wtf is wrong with some ppl :smh:
