### ISSUE TITLE
Watching and Listening command NOT working.

### ISSUE THREAD

**Issue by Markieyer** [appu1232/Discord-Selfbot#297]
![7jrabu9](https://user-images.githubusercontent.com/34459231/38398682-9453d1bc-3902-11e8-887f-da54aa0f89bb.png)
As you can see here, it says I set my status to "Watching an experiment"
However, when viewed on an alt account (Or any other account for this matter), this happens.
![hvotycx](https://user-images.githubusercontent.com/34459231/38398698-b65f98fe-3902-11e8-8267-aa9453206c26.png)
Any support?

**Comment by Gomido** [comment]
I also tested it, it works for a few seconds and then changes its status to 'playing' or 'online'.

**Comment by chenzw95** [comment]
Please see if the latest commit fixes this issue.

**Comment by chenzw95** [comment]
No reply after a week, I assume it has been fixed, given the emoji reaction.
