### ISSUE TITLE
Install error on Windows 7 Ult. 32-bit

### ISSUE THREAD

**Issue by MazariFox** [appu1232/Discord-Selfbot#298]
So I have no clue if im fking up or not.. Basically tried installing and... well Heres the console
> Checking/Installing requirements (takes some time on first install)...
> Collecting git+https://github.com/Rapptz/discord.py@rewrite (from -r requirement
> s.txt (line 1))
>   Cloning https://github.com/Rapptz/discord.py (to rewrite) to c:\users\mazari~1
> \appdata\local\temp\pip-n7_n2f3w-build
> Collecting prettytable==0.7.2 (from -r requirements.txt (line 2))
>   Using cached prettytable-0.7.2.tar.bz2
> Collecting requests==2.12.4 (from -r requirements.txt (line 3))
>   Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
> Exception:
> Traceback (most recent call last):
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\bas
> ecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\com
> mands\install.py", line 324, in run
>     requirement_set.prepare_files(finder)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\req
> \req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\req
> \req_set.py", line 620, in _prepare_file
>     session=self.session, hashes=hashes)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\dow
> nload.py", line 821, in unpack_url
>     hashes=hashes
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\dow
> nload.py", line 659, in unpack_http_url
>     hashes)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\dow
> nload.py", line 882, in _download_http_url
>     _download_url(resp, link, content_file, hashes)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\dow
> nload.py", line 603, in _download_url
>     hashes.check_against_chunks(downloaded_chunks)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\uti
> ls\hashes.py", line 46, in check_against_chunks
>     for chunk in chunks:
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\dow
> nload.py", line 571, in written_chunks
>     for chunk in chunks:
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\uti
> ls\ui.py", line 141, in iter
>     self.next(n)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\progress\__init__.py", line 73, in next
>     self.update()
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\progress\bar.py", line 79, in update
>     self.writeln(line)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\progress\helpers.py", line 68, in writeln
>     print(line, end='', file=self.file)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\colorama\ansitowin32.py", line 141, in write
>     self.write_and_convert(text)
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\colorama\ansitowin32.py", line 169, in write_and_convert
>     self.write_plain_text(text, cursor, len(text))
>   File "C:\Users\mazarifox\AppData\Roaming\Python\Python36\site-packages\pip\_ve
> ndor\colorama\ansitowin32.py", line 175, in write_plain_text
>     self.wrapped.flush()
> PermissionError: [WinError 31] A device attached to the system is not functionin
> g
> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-
> 8'>
> PermissionError: [WinError 31] A device attached to the system is not functionin
> g
> Requirements installation failed. Perhaps some dependency is missing or access w
> as denied? Possible solutions:
> - Run as administrator
> - Google the error
> - Visit the Discord server for help
> Press any key to exit.
>

**Comment by LyricLy** [comment]
This area is not for support. Try asking for help on the Discord server.
