### ISSUE TITLE
Server's user list doesn't work on serverinfo command

### ISSUE THREAD

**Issue by nanopulga** [appu1232/Discord-Selfbot#302]
When using ther serverinfo command, the option, where it appear "Users" it has a clickable test to the a Hastebin page with all the users from a server, doesn't work it says

`[List of all XX users in this server](Error with creating Hastebin. Status: 503)`
(XX is the number of server members)

![mxi1hga](https://user-images.githubusercontent.com/28354083/39059738-acf809b8-44bf-11e8-8cca-e249fa8f3dae.png)

The last time I used the command was on Monday it was working fine, but an hour ago I tried to use it and it doesn't work. I asked for a friend (who also uses the selfbot) and it happened the same thing. I still can't get a Hastebin page with the users list.
I hope the problem will get fixed soon or something. I really wanted to use it today. I don't know why this is happening.
Cheers and nice selfbot!

**Comment by shivaco** [comment]
Something wrong on Hastebin's end. Waiting will probably a solution.
