### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by NeonKNT** [appu1232/Discord-Selfbot#305]
When trying to install it on heroku, I am doing every step right but I end up with an error in the logs that says "Heroku environment detected, but config.json not found!"

**Comment by chenzw95** [comment]
We are addressing only issues with code here, and will not be able to assist with configuration issues arising from user error.

**Comment by Jaydan69** [comment]
Also happening to me although I doubt it is user error, unless I have somehow made the same error four times.
