### ISSUE TITLE
cannot load the mal.py extension & other

### ISSUE THREAD

**Issue by KingKunsama** [appu1232/Discord-Selfbot#306]
# MAL.PY
I have the mal.py extension and it's in my cogs folder, the selfbot tells me i can't load it
## another issue
my selfbot keeps telling me it's not advised to run it as admin, but i'm not
## image for both problems
![image](https://user-images.githubusercontent.com/38596349/39398628-7aae2580-4ade-11e8-95f3-1c2dc6b5e36f.png)

**Comment by chenzw95** [comment]
Not a bug, your environment is misconfigured.
