### ISSUE TITLE
Something went wrong error.

### ISSUE THREAD

**Issue by AwakenXD** [appu1232/Discord-Selfbot#308]
I am getting errors when I try to use half of the commands such as .ascii, .embed, etc and would not have these issues before. Now I also get spammed with "Something went wrong: 'Bot' object has no attribute 'default_status"

![image](https://user-images.githubusercontent.com/38859322/39453995-a3f9487e-4c8d-11e8-93db-adcdc783822a.png)

**Comment by chenzw95** [comment]
You have a syntax error in your configuration file(s). Please refer to the traceback.

**Comment by AwakenXD** [comment]
What is the traceback, I don't understand..
