### ISSUE TITLE
TypeError on startup

### ISSUE THREAD

**Issue by SightAnime** [appu1232/Discord-Selfbot#309]
I Tried Downloading And It Does Well Then At Some Point This Code Happens And I Cant Do Anything.
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
Im Am Confused Yarl?

**Comment by LyricLy** [comment]
yarl 1.2 contains a breaking change that has not yet been accounted for in aiohttp. Downgrade to a lower version.

This is all of the help I can provide, due to our policy on support.

**Comment by LyricLy** [comment]
I will leave this open for future users.

**Comment by enp0s25** [comment]
How do I downgrade?

**Comment by Feyko** [comment]
Hello
I have the same issue but i can't figure out how to downgrade yarl to 1.1.. please help ?

**Comment by architdate** [comment]
```pip install --upgrade yarl==1.1```

**Comment by OriginalNoel** [comment]
Where can i downgrade yarl?

**Comment by LyricLy** [comment]
Please read the above posts.
