### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Semichaotic** [appu1232/Discord-Selfbot#311]
When trying to launch the bot it asks for update. I type Y. Then that happens (See log)
Log:
Latest update:
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
remote: Counting objects: 5242, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5242 (delta 2), reused 7 (delta 2), pack-reused 5235
Receiving objects: 100% (5242/5242), 8.43 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (3665/3665), done.
error: unable to open object pack directory: .git/objects/pack: Permission denied
From https://github.com/appu1232/Discord-Selfbot
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
error: The following untracked working tree files would be overwritten by merge:
        .gitignore
        .travis.yml
        LICENSE
        Procfile
        README.md
        anims/example.txt
        appuselfbot.py
        cogs/cog_download.py
        cogs/customcmds.py
        cogs/debugger.py
        cogs/emoji.py
        cogs/fc.py
        cogs/fun.py
        cogs/google.py
        cogs/help.py
        cogs/imagedump.py
        cogs/keywordlog.py
        cogs/lockdown.py
        cogs/mal.py
        cogs/misc.py
        cogs/mod.py
        cogs/repl.py
        cogs/replacements.py
        cogs/serverinfo.py
        cogs/todo.py
        cogs/translate.py
        cogs/userinfo.py
        cogs/utility.py
        cogs/utils/LICENSE
        cogs/utils/allmsgs.py
        cogs/utils/checks.py
        cogs/utils/common.py
        cogs/utils/config.py
        cogs/utils/credit.txt
        cogs/utils/dataIO.py
        cogs/utils/image_dump.py
        cogs/utils/mal_char_find.py
        cogs/utils/menu.py
        cogs/utils/notify.py
        cogs/utils/save/hidden_channels.txt
        cogs/utils/save/largest_server.txt
        cogs/utils/save/mem_info.txt
        cogs/utils/save/same_discrim.txt
        cogs/utils/save/server_role_count.txt
        cogs/utils/save/server_share.txt
        cogs/utils/save/server_share_long.txt
        cogs/utils/save/stalker_percent.txt
        cogs/utils/save/total_users.txt
        cogs/utils/webhooks.py
        loopself.py
        requirements.txt
        run.bat
        run_linuxmac.sh
        settings/avatars.json.sample
        settings/commands.json.sample
        settings/config.json.sample
        settings/fc.json.sample
        settings/github.json.sample
        settings/ignored.json.sample
        settings/log.json.sample
        settings/moderation.json.sample
        settings/notify.json.sample
        settings/optional_config.json.sample
        settings/replacements.json.sample
        settings/todo.json.sample
Please move or remove them before you merge.
Aborting
Fetching origin
From https://github.com/appu1232/Discord-Selfbot
 * [new branch]      dev             -> origin/dev
 * [new branch]      log-context-fix -> origin/log-context-fix
 * [new tag]         v1.4.0          -> v1.4.0
 * [new tag]         v1.6.2          -> v1.6.2
 * [new tag]         v1.6.3          -> v1.6.3
 * [new tag]         v1.6.4          -> v1.6.4
 * [new tag]         v1.6.5          -> v1.6.5
 * [new tag]         v1.6.6          -> v1.6.6
 * [new tag]         v2.0.0          -> v2.0.0
 * [new tag]         v2.1.0          -> v2.1.0
HEAD is now at 7806c44 update disclaimers
'p...' is not recognized as an internal or external command,
operable program or batch file.
Checking/Installing requirements (takes some time on first install)...
Traceback (most recent call last):
  File "C:\Users\Ludde\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ludde\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ludde\AppData\Roaming\Python\Python35\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "C:\Users\Ludde\AppData\Roaming\Python\Python35\site-packages\pip\_internal\__init__.py", line 20, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
ImportError: No module named 'pip._vendor.urllib3'
Traceback (most recent call last):
  File "C:\Users\Ludde\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ludde\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ludde\AppData\Roaming\Python\Python35\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "C:\Users\Ludde\AppData\Roaming\Python\Python35\site-packages\pip\_internal\__init__.py", line 20, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
ImportError: No module named 'pip._vendor.urllib3'

**Comment by LyricLy** [comment]
This issue seems to arise from user error. Thus, we cannot support you with it.
