### ISSUE TITLE
Bot doesn't start with no changes

### ISSUE THREAD

**Issue by Kaktusboi** [appu1232/Discord-Selfbot#316]
When I'm runing the _sudo bash run_linuxmac.sh_ command it shows me this after a while:
https://i.imgur.com/miW2DDW.png

**Comment by chenzw95** [comment]
We do not support running the bot as root. For that matter, no ordinary program should ever be run as root without good reason.

**Comment by Kaktusboi** [comment]
Well, without _sudo_ it does this:

Traceback (most recent call last):
  File "appuselfbot.py", line 183, in <module>
    logger = set_log()
  File "appuselfbot.py", line 175, in set_log
    maxBytes=10**7, backupCount=5)
  File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/pi/Discord-Selfbot/settings/logs/bot.log'

Trying to run it as root was to fix the permission problems

**Comment by chenzw95** [comment]
You have already run the bot as root once before, so the permissions of some files are already incorrectly set to root ownership.

This is a misconfiguration on your end. You will have to either fix the file permissions manually or perform a clean install of the bot.
