### ISSUE TITLE
Problem setting up

### ISSUE THREAD

**Issue by tree-82** [appu1232/Discord-Selfbot#317]
keeps repeating this statement for a while:
Something went wrong: WebSocket connection is closed: no code, no reason.

and then repeats this:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000C7C1657EF0>

**Comment by kubilay12344** [comment]
Make sure that python is installed the correct way (not 100% sure if thats the issue)

**Comment by LyricLy** [comment]
This is not an error.
