### ISSUE TITLE
MASS DELETE DM MESSAGES

### ISSUE THREAD

**Issue by MacGyverinf** [appu1232/Discord-Selfbot#320]
Include a command to PURGE DMs either the entire dm history since before time, or in large chunks, silently...w/o interaction

**Comment by LyricLy** [comment]
You cannot delete other people's messages.

**Comment by MacGyverinf** [comment]
Not others

**Comment by MacGyverinf** [comment]
Not others, my messages in dm chats

**Comment by Bluscream** [comment]
`>d <amount>`

**Comment by LyricLy** [comment]
Yes, you are using the wrong command.
