### ISSUE TITLE
Can't Open Files

### ISSUE THREAD

**Issue by CapnS** [appu1232/Discord-Selfbot#323]
How do I open the "Fun.py" file and the "misc.py" file. I am trying to learn how to make discord bots and your extensive bot is very helpful with this, but I can't seem to edit those two files. I think it has something to do with the emojis. How did you get around this

**Comment by LyricLy** [comment]
Try using another editor. Emoji should not be causing errors with any capable editor. Less capable ones such as Microsoft's Notepad may struggle.
