### ISSUE TITLE
Won't install.

### ISSUE THREAD

**Issue by Deksastara** [appu1232/Discord-Selfbot#325]
Console:
Checking/Installing requirements (takes some time on first install)...
Collecting git+https://github.com/Rapptz/discord.py@rewrite (from -r requirement
s.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to c:\users
\pesce\appdata\local\temp\pip-req-build-8x56wymw
Collecting prettytable==0.7.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f
052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Collecting requests==2.12.4 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ed/9e/60cc074968c095f728f0
d8d28370e8d396fa60afb7582735563cccf223dd/requests-2.12.4-py2.py3-none-any.whl (5
76kB)
Could not install packages due to an EnvironmentError: [WinError 31] A device at
tached to the system is not functioning
Check the permissions.

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-
8'>
PermissionError: [WinError 31] A device attached to the system is not functionin
g
Requirements installation failed. Perhaps some dependency is missing or access w
as denied? Possible solutions:
- Run as administrator
- Google the error
- Visit the Discord server for help
Press any key to exit.

**Comment by LyricLy** [comment]
Stop using Python 3.6.
