### ISSUE TITLE
Suddenly unable to start the bot?

### ISSUE THREAD

**Issue by omelody213** [appu1232/Discord-Selfbot#326]
I'm sorry if this does not belong here, but since last night I've been running into this problem. It worked fine before last night and the only thing I can think of that might've screwed me is a Windows 10 update. Whenever I attempt to start the bot, I receive this.

"  Could not find a version that satisfies the requirement aiohttp<3.4.0,>=3.3.0 (from discord.py==1.0.0a1473+g607771c->-r requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a3, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp<3.4.0,>=3.3.0 (from discord.py==1.0.0a1473+g607771c->-r requirements.txt (line 1))"
![download](https://user-images.githubusercontent.com/40154055/41208680-d2de7e92-6d1d-11e8-94f0-8f0721d40830.png)

Any ideas how I can fix this?

**Comment by Markieyer** [comment]
I am having the same exact issue

**Comment by KaosBass** [comment]
Same

**Comment by LyricLy** [comment]
I believe this is an issue with a new discord.py update, and we will try to fix it as soon as possible.

**Comment by LyricLy** [comment]
In the meanwhile, try doing `pip install aiohttp --upgrade` and update the bot's files manually with `git clone`.

**Comment by skoof** [comment]
i'm having the same issue. and i'm fairly new to most coding things so i don't know how to "update the bot's files manually with git clone". also the discord invite link on the wiki says it's expired jsyk

**Comment by ZackaryH8** [comment]
Still having issues

**Comment by skoof** [comment]
the "temporal hotfix", from OuroboricCycle, seems to have worked for me

**Comment by ZackaryH8** [comment]
Mine is still having problems after the fix...

**Comment by omelody213** [comment]
I'm probably being an idiot and doing something wrong, however this is what I get whenever I do what LyricLy said.
[Error screenshot](http://prntscr.com/jtrtpx)

**Comment by omelody213** [comment]
#

**Comment by omelody213** [comment]
I was about to close this, but won't incase the same problem arises. I will say that #329 fixed my issue (for now.)

**Comment by LyricLy** [comment]
It would seem as though your installation of pip is broken. Separate issue, but you should really fix that as well.

**Comment by ZackaryH8** [comment]
Found A way to sort it, Run the Mac one on windows and it is sorted

**Comment by omelody213** [comment]
I'll sort it out. Thanks.

**Comment by OuroboricCycle** [comment]
@ZackaryH8 Weird, have you made sure that aiohttp==2.3.10 is in your requirement.txt?

That message is usually the one that popped up _before_ having it for me
if it somehow still doesn’t work try adding it before line 1(git+https://...)

**Comment by appu1232** [comment]
Added the hotfix to the latest version. Should be working now on your next run (update).

**Comment by appu1232** [comment]
Additionally, upgrade your python version to 3.6 (make sure to add to PATH).

**Comment by Neswo** [comment]
same

**Comment by illexals** [comment]
i've this issue please help client_session: <aiohttp.client.ClientSession object at 0x000001B631A6C780>

**Comment by illexals** [comment]
Failed to transfer custom cogs to custom_cogs folder. Error: Expecting value: line 1 column 1 (char 0)

**Comment by illexals** [comment]
this too ^^
