### ISSUE TITLE
Heroku deploy fail ("No matching aiohttp version")

### ISSUE THREAD

**Issue by OuroboricCycle** [appu1232/Discord-Selfbot#327]
I've recently attempted to deploy directly from my github fork of the bot, doing the same steps as would normally be done when using the Heroku CLI locally, however, there seems to be an issue when attempting to collect aiohttp when fetching the requirements

I'm not sure if this is an issue that should be opened on here or on the discord.py repository, since the requirement seems to be linked to it, but just in case i'll attach the build log in a txt
[Heroku_Build_Log.txt](https://github.com/appu1232/Discord-Selfbot/files/2089851/Heroku_Build_Log.txt)

**Comment by skoof** [comment]
https://github.com/appu1232/Discord-Selfbot/issues/326

**Comment by OuroboricCycle** [comment]
Thanks for the heads-up

**Reason for closing:**Clone of issue #326
