### ISSUE TITLE
Installation.

### ISSUE THREAD

**Issue by Deksastara** [appu1232/Discord-Selfbot#328]
![screenshot_2](https://user-images.githubusercontent.com/30935997/41231526-eca3aa70-6d48-11e8-8362-5f31a2d8d81a.png)

Checking/Installing requirements (takes some time on first install)...
Collecting git+https://github.com/Rapptz/discord.py@rewrite (from -r requirement
s.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to c:\users
\pesce\appdata\local\temp\pip-req-build-m_1bnh6c
Collecting prettytable==0.7.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f
052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Collecting requests==2.12.4 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ed/9e/60cc074968c095f728f
0d8d28370e8d396fa60afb7582735563cccf223dd/requests-2.12.4-py2.py3-none-any.whl
Collecting beautifulsoup4==4.5.3 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/af/a3/9e803f838b3eeb313d4
5d916d4387cda8572c92e1aafeb53fd43ddb5da2c/beautifulsoup4-4.5.3-py3-none-any.whl
Collecting strawpy==1.1 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/03/13/45e0961af59bec25cf0
ba4c6684b636d82e7bab62480f8b157d48606fe16/strawpy-1.1.zip
Collecting lxml==3.8.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/30/31/8165205328d1e5b8dfd
5db8bc7b4de09f74a6d680f37b9d50168fdb9d309/lxml-3.8.0-cp35-cp35m-win32.whl
Collecting psutil==5.2.1 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/76/3b/2e6b3306dd2927fef9c
81fdc29bc450beeb6f4bfe4cddec80260ab042900/psutil-5.2.1-cp35-cp35m-win32.whl
Collecting GitPython==2.1.3 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/49/86/a4af08e0dbd8b187632
5efa12e7d041e471e3d33fa2f6d947d40a963b117/GitPython-2.1.3-py2.py3-none-any.whl
Collecting Pillow==4.2.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/71/5f/f2121526ce6cebdbd72
6917d7a23da13cd6e22645358d89b9af3e199ab91/Pillow-4.2.1-cp35-cp35m-win32.whl
Collecting pyfiglet==0.7.5 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/a2/65/4e29896298591d748f5
ce4e96642b8a0a876b64ed7226b5ae65fae81e5c9/pyfiglet-0.7.5.tar.gz
Collecting tokage==1.0.0 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/3c/64/de45a2488f6ac7b3789
258060a414e100d4b37ddc03570d2c057fadcef6b/Tokage-1.0.0.tar.gz
Collecting pytz==2017.2 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/55/62/e7cd0e15b76062d2984
13f14bb4ec3cd8568a22d274427f9c3c7286969f4/pytz-2017.2-py2.py3-none-any.whl
Collecting PyGithub==1.34 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/43/cb/35fbf0e380595dab772
0e6b4a9f8f19c5947b90e84fa23b7cedea945222e/PyGithub-1.34.tar.gz
Collecting aiohttp<3.4.0,>=3.3.0 (from discord.py==1.0.0a1473+g607771c->-r requi
rements.txt (line 1))
  Could not find a version that satisfies the requirement aiohttp<3.4.0,>=3.3.0
(from discord.py==1.0.0a1473+g607771c->-r requirements.txt (line 1)) (from versi
ons: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2,
 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.
8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0,
 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3,
 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2,
 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1,
 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.2
2.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2,
 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2,
 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.
0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1
.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a3, 2.3.0a4
, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.
3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp<3.4.0,>=3.3.0 (from discord.py==1.0.0
a1473+g607771c->-r requirements.txt (line 1))
Requirements installation failed. Perhaps some dependency is missing or access w
as denied? Possible solutions:
- Run as administrator
- Google the error
- Visit the Discord server for help
Press any key to exit.

**Comment by skoof** [comment]
https://github.com/appu1232/Discord-Selfbot/issues/326
