### ISSUE TITLE
Being able to use | in embeds

### ISSUE THREAD

**Issue by cook1e0** [appu1232/Discord-Selfbot#331]
You can't use the | symbol due to it being use to divide embed properties. Maybe use something else to divide them?

**Comment by Bluscream** [comment]
try \|

**Comment by cook1e0** [comment]
doesn't work, its something with how the bot works than discord formatting.

**Comment by LyricLy** [comment]
Anything we use as a divider would then have the same issue. The pipe was chosen due to it not being needed in most normal use, but escaping it should work.

**Comment by CX-9000** [comment]
@LyricLy do I need to uninstall the python that comes with the Mac to install python3 or can I just install python3?

**Comment by LyricLy** [comment]
Don't comment to random issues.
