### ISSUE TITLE
windows 31 error A device isnt functioning properly

### ISSUE THREAD

**Issue by Nujiao** [appu1232/Discord-Selfbot#339]
the bot used to work, i updated python and now its just giving me this error

**Comment by appu1232** [comment]
Try uninstalling Python then installing Python 3.5.3. Make sure you check "add to PATH" on install. To confirm you have 3.5.3, open a command window and type `python -V` to check the version.

**Comment by LyricLy** [comment]
Yes, Python 3.7 will not work.
