### ISSUE TITLE
Version Error? (MAC)

### ISSUE THREAD

**Issue by CX-9000** [appu1232/Discord-Selfbot#340]
<img width="1440" alt="screen shot 2018-06-29 at 04 25 07" src="https://user-images.githubusercontent.com/40681585/42071690-8ad75052-7b54-11e8-84c9-cc3674c768bf.png">
 

I have installed python 3.5.3 and yet it seems to show 2.7 even tho it's no where to be found on apps or through command line 😕

**Comment by LyricLy** [comment]
Use `python3`, not `python`. Python 2 comes preinstalled on Mac.
