### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by LastRoze** [appu1232/Discord-Selfbot#341]
Help, just got this Error today.

- Python 3.5.3
- Pip 9.0.1

![capture](https://user-images.githubusercontent.com/9519234/42124954-800f40de-7c9f-11e8-9594-169e7f08012c.PNG)

**Comment by xyn-n** [comment]
I have this issue, too.

**Comment by nanopulga** [comment]
Same here...

**Comment by ggrey22** [comment]
I'm also having this issue

**Comment by professorshinonome** [comment]
Also experiencing this. Quite a few of the bot's commands error, not sure if that's tied to this at all or not.

**Comment by Blitzsy** [comment]
Discord.py rewrite committed a change which broke something in the selfbot. You will need to wait until a fix is made on the selfbot side. I managed to find a temporary workaround by changing the pip requirements.txt.

Find `
git+https://github.com/Rapptz/discord.py@rewrite` 
and replace it with `git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233`

**Comment by LastRoze** [comment]
@Blitzsy Thanks for the workaround man, really appreciated it.

**Comment by LyricLy** [comment]
The issue is likely to be fixed soon on discord.py's side. It seems as though a fix has already been PRed.

**Comment by TastyCookies124** [comment]
Yay!!!! It worked Thanks Blitzsy

**Comment by MacGyverinf** [comment]
this also worked for me as well
`git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233`

thanks

**Comment by appu1232** [comment]
Just pushed the discord.py version rollback to master. Should be fixed now if you accept the update next time you run the bot.
