### ISSUE TITLE
Selfbot stuck at starting bot ONLY on Raspian

### ISSUE THREAD

**Issue by professorshinonome** [appu1232/Discord-Selfbot#342]
So I have no idea what the source of this issue is, or if I should even post this here because it is a device specific issue, but I'd like to bring it up to get some help if possible. When I run the bot in multiple linux environments, it runs and logs in just fine. When I try to run the bot in Raspbian on my Raspberry Pi however, the bot just hangs on "Starting bot..."

It's not the network, and it's not the device, because I tried it on my friend's Pi, and we experienced the same issue. Any idea how to even begin to debug this issue? There are no errors, it just hangs.

**Comment by chenzw95** [comment]
This seems to be an issue specific to Raspbian or Raspberry Pis in general, as you have confirmed; this is unfortunately beyond the scope of this issue tracker.
