### ISSUE TITLE
Bot keeps restarting after latest update

### ISSUE THREAD

**Issue by cook1e0** [appu1232/Discord-Selfbot#345]
![image](https://user-images.githubusercontent.com/8332033/42181330-c3588192-7e3a-11e8-8e79-ac4b663332ad.png)

**Comment by cook1e0** [comment]
nvm stopped after restarting after a few more times

**Comment by PorpoisefullyOffensive** [comment]
I'm having the same issue, but it's not stopping and has been almost 20 minutes. I dont get errors or anything, there's usually a couple minutes between restarts, and any commands i enter will go through as soon as it restarts, but after that they wont do anything again until it restarts again. if that makes sense.
![github issue](https://user-images.githubusercontent.com/47234857/52102088-8f486600-25ac-11e9-8297-bc6faa02f3c2.png)
