### ISSUE TITLE
Problem with the startup

### ISSUE THREAD

**Issue by Kex1016** [appu1232/Discord-Selfbot#350]
I downloaded the bot. Unzipped it. Did everything as it said in the guide. **But**, after I finished the setup, it started looping back into the token section and now everytime I enter the token this error displays and it loops back again:
https://fire-has.a-shit.stream/4c7GWSp.png

**Comment by Kex1016** [comment]
Also, on a fresh startup, this error message shows up:
https://facebook.is-tra.sh/iEyg27u.png

**Comment by appu1232** [comment]
1. Update the bot to the latest. It shouldn't give the `prettytable not found` error if you're on the latest.
2. Seems like you are entering the wrong value for the token. Can't think of any other reason it would keep asking you to enter it.

**Comment by Kex1016** [comment]
Both of these aren't probably the problem, I downloaded the latest version today, and I've given the correct token each time, so I have no clue :/

**Comment by Kex1016** [comment]
Both of these aren't probably the problem, I downloaded the latest version today, and I've given the correct token each time, so I have no clue :/

**Comment by LyricLy** [comment]
Is this still an issue?

**Comment by Kex1016** [comment]
yes, I just checked and it still doesn't work.
