### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by Jeremy2131** [appu1232/Discord-Selfbot#358]
Tried to start bot today and I've memory error message too much
![1](https://user-images.githubusercontent.com/20999549/42689256-2adc904a-86a8-11e8-887d-b9ff7731c909.png)
And in the end that writes "Unclosed client session"
Okay I have a new error after several attempts to start it
![1](https://user-images.githubusercontent.com/20999549/42689476-1dc2c4a0-86a9-11e8-8c66-ecf30703a544.png)

**Comment by Jeremy2131** [comment]
Any help please?

**Comment by samdivaio** [comment]
Your IP is probably banned.

**Comment by Jeremy2131** [comment]
@samdivaio are you sure?
