### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by TheAnarchist00** [appu1232/Discord-Selfbot#360]
![why_god_why](https://user-images.githubusercontent.com/41229917/42735784-f608c4e4-887b-11e8-81b8-40012e63b163.PNG)
am i doing something wrong?

**Comment by LyricLy** [comment]
Why are you running the bot from what seems to be directly from a .zip?

**Comment by TheAnarchist00** [comment]
Yeah i found out the problem. I was using pip freeze so it tried to get the discord api instead of the rewrite version, the one i was using.
