### ISSUE TITLE
the sudo is not working

### ISSUE THREAD

**Issue by norwegen92** [appu1232/Discord-Selfbot#363]
i'm trying to get the requirements.txt to work, since when i click on run it does not run, it shows up that it doesn't response to requirements.txt, when i try to type "sudo -H pip install -r requirements.txt" it does not find the file. but it's in the folder.. any idea how to fix this?

**Comment by appu1232** [comment]
Will need some screenshots because I'm not sure based on just what you've said. I assume you've unzipped the folder and haven't moved anything.
