### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amohi9046** [appu1232/Discord-Selfbot#370]
Command "C:\Users\moham\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\moham\\AppData\\Local\\Temp\\pip-install-pkq7fhww\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\moham\AppData\Local\Temp\pip-record-mj5uk329\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\moham\AppData\Local\Temp\pip-install-pkq7fhww\lxml\
^ I got this error when I tried to run it for the first time.

**Comment by LyricLy** [comment]
That doesn't seem to be the entire error.

**Comment by amohi9046** [comment]
I found out that I was using python 7 and that's what the problem was.
