### ISSUE TITLE
cant update 

### ISSUE THREAD

**Issue by TastyCookies124** [appu1232/Discord-Selfbot#371]
So every time I use a bunch of diff commands like poll or google image search even ascii it gives me an error so I have tried to update but I get some strange stuff. idk if its on my side but here is what im getting.

`settings/avatars.json.sample
        settings/commands.json.sample
        settings/config.json.sample
        settings/fc.json.sample
        settings/github.json.sample
        settings/ignored.json.sample
        settings/log.json.sample
        settings/moderation.json.sample
        settings/notify.json.sample
        settings/optional_config.json.sample
        settings/replacements.json.sample
        settings/todo.json.sample
Please move or remove them before you can merge.
Aborting
Pull failed, attempting to hard reset to origin HEAD (settings are still saved)
Fetching origin
fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Update succeeded
Checking requirements...
Using pip as a python3 module
Upgrading requirements
Collecting git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233 (from -r requirements.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to 184c4302c7fe17a31893f0accf197c975200d233) to /tmp/pip-id03q7ay-build
  Could not find a tag or branch '184c4302c7fe17a31893f0accf197c975200d233', assuming commit.
Requirement already up-to-date: requests==2.12.4 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: beautifulsoup4==4.5.3 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: strawpy==1.1 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: lxml==3.8.0 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: psutil==5.2.1 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: GitPython==2.1.3 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: Pillow==4.2.1 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: pyfiglet==0.7.5 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: tokage==1.0.0 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pytz==2017.2 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: PyGithub==1.34 in /root/.local/lib/python3.5/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: aiohttp<3.4.0,>=3.3.0 in /root/.local/lib/python3.5/site-packages (from discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<6.0,>=5.0 in /root/.local/lib/python3.5/site-packages (from discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: gitdb2>=2.0.0 in /root/.local/lib/python3.5/site-packages (from GitPython==2.1.3->-r requirements.txt (line 7))
Requirement already up-to-date: olefile in /root/.local/lib/python3.5/site-packages (from Pillow==4.2.1->-r requirements.txt (line 8))
Requirement already up-to-date: pyjwt in /root/.local/lib/python3.5/site-packages (from PyGithub==1.34->-r requirements.txt (line 12))
Requirement already up-to-date: yarl<2.0,>=1.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: chardet<4.0,>=2.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: attrs>=17.3.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout<4.0,>=3.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: multidict<5.0,>=4.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: idna-ssl>=1.0 in /root/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: smmap2>=2.0.0 in /root/.local/lib/python3.5/site-packages (from gitdb2>=2.0.0->GitPython==2.1.3->-r requirements.txt (line 7))
Requirement already up-to-date: idna>=2.0 in /root/.local/lib/python3.5/site-packages (from yarl<2.0,>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py===1.0.0a1477+g184c430->-r requirements.txt (line 1))
Installing collected packages: discord.py
  Found existing installation: discord.py 1.0.0a1477+g184c430
    Uninstalling discord.py-1.0.0a1477+g184c430:
      Successfully uninstalled discord.py-1.0.0a1477+g184c430
  Running setup.py install for discord.py ... done
Successfully installed discord.py-1.0.0a1477+g184c430
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Starting bot...
It is not advised to run the bot with root privileges.
`

**Comment by TastyCookies124** [comment]
so that text is a bunch ill share a screenshot. I also get an error when logged in "Something went wrong"
over and over again ( bottom screenshot ) sorry to bother again.
![image](https://user-images.githubusercontent.com/25892061/43580917-a1f7471e-961c-11e8-8343-d92d4b06dc7d.png)

![image](https://user-images.githubusercontent.com/25892061/43580943-bbfcc1ac-961c-11e8-8e35-f493b4c71ba0.png)

**Comment by TastyCookies124** [comment]
Ok I’ll try that thank you.  Yeah when I try to update using command it gives error and I assumed when it said “pull failed attempting to hard reset to origin head” I thought it was failing but thanks.

**Comment by TastyCookies124** [comment]
@LyricLy So I have set up the `optional_config.json` but still getting the same error. 

![image](https://user-images.githubusercontent.com/25892061/43990670-11e93a1a-9d24-11e8-880a-9cb9c289fdd8.png)

**Comment by LyricLy** [comment]
Looks like your optional_config.json file is still malformed. Send it here?
