### ISSUE TITLE
Can't start the bot with horoku

### ISSUE THREAD

**Issue by AngelAsukii** [appu1232/Discord-Selfbot#372]
![screenshot - 03_08_2018 14_14_09](https://user-images.githubusercontent.com/42059981/43642368-8d663ef2-9727-11e8-964d-b94fccf64c7b.png)
Help me please

**Comment by LyricLy** [comment]
You have the wrong version of Python. 3.5.3 or higher is required.

**Comment by Mystic4TW** [comment]
Try changing the version in the runtime.txt from `python-3.5.2` to `python-3.6.1`
