### ISSUE TITLE
Heroku environment detected, but no config.json.

### ISSUE THREAD

**Issue by chadismydad** [appu1232/Discord-Selfbot#374]
Hi, I'm trying to start the self bot using heroku, but whenever I start the worker the logs are spammed with this error:
`2018-08-10T07:33:21.068936+00:00 app[worker.1]: Error: Heroku environment detected, but config.json not found!
2018-08-10T07:33:21.069072+00:00 app[worker.1]: This is usually due to user error during Heroku setup.`

I followed the heroku tutorial exactly, except that in runtime.txt I put in "python-3.6.6"
Does anyone know what is going on here?

**Comment by therapys** [comment]
did u close this because u got it to work? i have the same problem

**Comment by chadismydad** [comment]
Yes I did, it was a stupid mistake on my part. Just make sure that at least the config.json in the settings folder does not have a .sample extension. I personally took off the .sample extension from every config file in there.

**Comment by therapys** [comment]
theres already a config.json what do i do?
