### ISSUE TITLE
Heroku dyno using too much memory

### ISSUE THREAD

**Issue by chadismydad** [appu1232/Discord-Selfbot#376]
I've gotten the bot to work correctly in Heroku, but running a single command takes minutes.
In the console, this error shows frequently:
`2018-08-10T22:14:57.940218+00:00 heroku[worker.1]: Process running mem=650M(127.1%)
2018-08-10T22:14:57.940390+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)`

If anyone has the bot working in Heroku without this error, I'd like to know how you did it.

**Comment by therapys** [comment]
how do u even host it on heroku add me on discord mx#0010 i need help please

**Comment by Macley-Kun** [comment]
It's just that you have alot of servers/channels. Some of these bots happen to use more memory than others. Nothing to be afraid of because the maximum is 1GB. So your well in the clear.

**Comment by chadismydad** [comment]
Yeah, that's true. It never uses a full gigabyte, but it takes like 5 minutes to get a response from a command if any at all.

**Comment by Macley-Kun** [comment]
Reduce amount of servers you are in, or use a VPS with more core/memory/faster storage.
