### ISSUE TITLE
cant start the bot

### ISSUE THREAD

**Issue by Cemocan36** [appu1232/Discord-Selfbot#377]
![screenshot_123](https://user-images.githubusercontent.com/42295927/43991534-845d4c8c-9d77-11e8-97fd-be7ae60018af.png)

getting this issue for a long time now.

**Comment by LyricLy** [comment]
You have the wrong version of Python.

**Comment by Cemocan36** [comment]
i have python 3.5 (64bit)

**Comment by LyricLy** [comment]
You need 3.5.3 to 3.6.6.
