### ISSUE TITLE
heroku 

### ISSUE THREAD

**Issue by therapys** [appu1232/Discord-Selfbot#378]
someone help please

![screenshot_5](https://user-images.githubusercontent.com/41189911/43998264-83a97fd4-9da6-11e8-86cc-51d7df9e5206.png)

**Comment by LyricLy** [comment]
The bot must be run locally before putting it on Heroku.

**Comment by therapys** [comment]
i did run it locally before i put it in heroku

**Comment by LyricLy** [comment]
Are you sure that you ran it locally, set it up and then used those files exactly to set up Heroku?

**Comment by KidoToshiro** [comment]
**Delete** the `.gitignore` file in the selfbot folder.
