### ISSUE TITLE
Something went wrong: WebSocket connection is closed: code = 1006

### ISSUE THREAD

**Issue by NitroPlayz** [appu1232/Discord-Selfbot#380]
![appuerror](https://user-images.githubusercontent.com/42419023/44167159-b332f080-a0cd-11e8-8c6a-c60a4d2e1775.PNG)
This error keeps on looping itself and commands don't work

**Comment by steve3743** [comment]
Ye, samething still happens to me, and my internet connection is fast. 🤔

**Comment by NitroPlayz** [comment]
Yea i have ethernet so my internet connection is fast, i also tried using wifi but still it didn't work

**Comment by shivaco** [comment]
Seems to be problems with connecting to Discord.

**Comment by NitroPlayz** [comment]
So is there no way I can fix it?

**Comment by appu1232** [comment]
Yea it's just an issue with your connection to Discord. Not much can be done.

**Comment by Markieyer** [comment]
If it helps anybody, I had this issue whenever my VPN connected or disconnected
So

**Comment by Markieyer** [comment]
![cmd_2018-08-20_15-13-30](https://user-images.githubusercontent.com/34459231/44364256-1fc23c80-a48c-11e8-9969-11065a07704f.png)
Receiving another error when I leave the selfbot alone, it keeps repeating the same errors, There's gotta be a reason for this

**Comment by Markieyer** [comment]
UPDATE: 
Problem solved on my side, I redownloaded the self-bot and set it up, and it works perfectly fine with no errors now, try redownloading it, and trying that one
I hope it works for you too!

**Comment by steve3743** [comment]
I downloaded it and re-installed it, not sure how that was supposed to fix the problem. But, I did find something of interest: the token field under applications/local storage is gone:

![discord_2018-08-20_17-30-10](https://user-images.githubusercontent.com/20365207/44367873-070f5200-a49f-11e8-9764-500bc21aa5b8.png)

**Comment by NitroPlayz** [comment]
Yea the token is gone, weird and I reinstalled the sbot like 5 times and it still didn't work

**Comment by appu1232** [comment]
Check the wiki page here, there is a new way to get the token.
