### ISSUE TITLE
Something went really wrong, I'm unable to find a fix

### ISSUE THREAD

**Issue by palaadynamo** [appu1232/Discord-Selfbot#381]
I got the right version of phyton
and then when i launch the bot, it shows this error all over again
Requirement already up-to-date: requests==2.12.4 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: beautifulsoup4==4.5.3 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: strawpy==1.1 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: lxml==3.8.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: psutil==5.2.1 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: GitPython==2.1.3 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: Pillow==4.2.1 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: pyfiglet==0.7.5 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: tokage==1.0.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pytz==2017.2 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: PyGithub==1.34 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: aiohttp<3.4.0,>=3.3.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: websockets<6.0,>=5.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: gitdb2>=2.0.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from GitPython==2.1.3->-r requirements.txt (line 7))
Requirement already up-to-date: olefile in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from Pillow==4.2.1->-r requirements.txt (line 8))
Requirement already up-to-date: pyjwt in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from PyGithub==1.34->-r requirements.txt (line 12))
Requirement already up-to-date: idna-ssl>=1.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout<4.0,>=3.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: multidict<5.0,>=4.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: yarl<2.0,>=1.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: attrs>=17.3.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: chardet<4.0,>=2.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Requirement already up-to-date: smmap2>=2.0.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from gitdb2>=2.0.0->GitPython==2.1.3->-r requirements.txt (line 7))
Requirement already up-to-date: idna>=2.0 in /Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages (from idna-ssl>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
Installing collected packages: discord.py
  Found existing installation: discord.py 1.0.0a1477+g184c430
    Uninstalling discord.py-1.0.0a1477+g184c430:
      Successfully uninstalled discord.py-1.0.0a1477+g184c430
  Running setup.py install for discord.py ... done
Successfully installed discord.py-1.0.0a1477+g184c430

**Comment by LyricLy** [comment]
What part of this looks like an error to you? All it says is that it successfully updated discord.py.

**Comment by palaadynamo** [comment]
I repeats itself forever

**Comment by palaadynamo** [comment]
I think ut said something about line 911

**Comment by palaadynamo** [comment]
Let ne try again for more info

**Comment by palaadynamo** [comment]
Thanks for responding

**Comment by palaadynamo** [comment]
This is what i found as well 
**_The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "appuselfbot.py", line 911, in <module>
    bot.run(token, bot=False)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 568, in run
    return task.result()
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 475, in start
    await self.login(*args, bot=bot)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/discord/client.py", line 346, in login
    await self.http.static_login(token, bot=bot)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 247, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/discord/http.py", line 154, in request
    async with self._session.request(method, url, **kwargs) as r:
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/client.py", line 366, in _request
    timeout=timeout
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Users/paladynamovincent/Library/Python/3.6/lib/python/site-packages/aiohttp/connector.py", line 827, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1119cfe10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x112632c88>
Task was destroyed but it is pending!
task: <Task pending coro=<Debugger.redirection_clock() running at /Users/paladynamovincent/Documents/SELFBOT/cogs/debugger.py:377> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1126f66d8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Todo.todo_timer() running at /Users/paladynamovincent/Documents/SELFBOT/cogs/todo.py:223> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1126f68e8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<game_and_avatar() running at appuselfbot.py:759> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1126f6978>()]>>
Traceback (most recent call last):_**
