### ISSUE TITLE
There is no token ):

### ISSUE THREAD

**Issue by RazorApple** [appu1232/Discord-Selfbot#382]
There is no Token in the Local storage ): ):

**Comment by Lythed** [comment]
Go to https://discordapp.com/developers/applications/ , log in to your account.

Inspect element, Application, Local Storage, You have now the Token.
![untitled](https://user-images.githubusercontent.com/35495389/44302841-4ddf3980-a331-11e8-8d47-bc02621eb50c.png)

**Comment by Markieyer** [comment]
Another way to do this is by opening inspect element, going to application, Local Storage, then refreshing Discord with Ctrl + R

**Comment by RazorApple** [comment]
Before it was not there. And it does not look like the top screen shot

Markieyer. To have it show for me I needed to go into local storage and then click ctrl + r
Otherwise it did not show
@Markieyer  Thanks
