### ISSUE TITLE
Unable to purge / delete due to messages not being loaded. Could this be corrected?

### ISSUE THREAD

**Issue by greatsalmonrun** [appu1232/Discord-Selfbot#387]
The purge and delete commands seem to not delete the specified amount, it only deletes messages on the current page and you have to scroll up to load more and run the command again, and sometimes it doesn't work after loading more messages.

If this is to not hit a rate limit, perhaps there can be a slower purge and delete command that truly deletes the specified amount (or all) messages? This is a greatly needed feature!

**Comment by LyricLy** [comment]
"the current page" isn't even a concept that the bot can understand, so this seems confusing to me. Ratelimits don't cause less messages to be deleted normally.
