### ISSUE TITLE
Can't react with text that has repeating characters

### ISSUE THREAD

**Issue by Rerd** [appu1232/Discord-Selfbot#389]
When I use the react command with something such as "asd", it works, but once I use the react command with something such as "aasd", which has repeating text, I get an error. Once that happens, other commands such as restart or quit stop working repeating the same error on the console.

[Example](https://youtu.be/ntBmOXbe1fU)
Error:
`Ignoring exception in on_command_error`
`Traceback (most recent call last):`
`  File "C:\Users\(my user)\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 220, in _run_event`
`    await coro(*args, **kwargs)`
`  File "appuselfbot.py", line 388, in on_command_error`
`    print("Ignoring exception in command {}".format(ctx.command.name))`
`PermissionError: [WinError 31] A device attached to the system is not functioning`

**Comment by LyricLy** [comment]
I know of this issue happening with Python version 3.6 on Windows; try 3.5.3.

**Comment by Rerd** [comment]
Thanks, fixed.
