### ISSUE TITLE
Critical problem

### ISSUE THREAD

**Issue by Jeremy2131** [appu1232/Discord-Selfbot#390]
![1](https://user-images.githubusercontent.com/20999549/44504198-1959dd80-a6a3-11e8-826a-2acd45321250.png)
When I tried to create the server with "serverload"

**Comment by Jeremy2131** [comment]
@LyricLy this is a screenshot lol,I got 2 these messages.

**Comment by Jeremy2131** [comment]
![1](https://user-images.githubusercontent.com/20999549/44545948-1ef50900-a71f-11e8-9b95-54d48a9a202b.png)

**Comment by LyricLy** [comment]
This isn't the place for help with custom cogs, either.
