### ISSUE TITLE
Visual Studio Error Libxml2? NVM THIS WAS FIXED, IM JUST STUPID AND CANT SEARCH FOR STUFF, MARK AS CLOSED OR DELETE IT

### ISSUE THREAD

**Issue by LuxTheLord** [appu1232/Discord-Selfbot#392]
This is the Entire Log for my error

Checking/Installing requirements (takes some time on first install)...
Collecting git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233 (from -r requirements.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to revision 184c4302c7fe17a31893f0accf197c975200d233) to c:\users\amonp\appdata\local\temp\pip-req-build-m97_7l4c
Requirement already satisfied: requests==2.12.4 in c:\users\amonp\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 2)) (2.12.4)
Requirement already satisfied: beautifulsoup4==4.5.3 in c:\users\amonp\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 3)) (4.5.3)
Requirement already satisfied: strawpy==1.1 in c:\users\amonp\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 4)) (1.1)
Collecting lxml==3.8.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/20/b3/9f245de14b7696e2d2a386c0b09032a2ff6625270761d6543827e667d8de/lxml-3.8.0.tar.gz
Collecting psutil==5.2.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/b8/47/c85fbcd23f40892db6ecc88782beb6ee66d22008c2f9821d777cb1984240/psutil-5.2.1.tar.gz
Collecting GitPython==2.1.3 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/49/86/a4af08e0dbd8b1876325efa12e7d041e471e3d33fa2f6d947d40a963b117/GitPython-2.1.3-py2.py3-none-any.whl
Collecting Pillow==4.2.1 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/55/aa/f7f983fb72710a9daa4b3374b7c160091d3f94f5c09221f9336ade9027f3/Pillow-4.2.1.tar.gz
Collecting pyfiglet==0.7.5 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/a2/65/4e29896298591d748f5ce4e96642b8a0a876b64ed7226b5ae65fae81e5c9/pyfiglet-0.7.5.tar.gz
Collecting tokage==1.0.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/3c/64/de45a2488f6ac7b3789258060a414e100d4b37ddc03570d2c057fadcef6b/Tokage-1.0.0.tar.gz
Collecting pytz==2017.2 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/55/62/e7cd0e15b76062d298413f14bb4ec3cd8568a22d274427f9c3c7286969f4/pytz-2017.2-py2.py3-none-any.whl
Collecting PyGithub==1.34 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/43/cb/35fbf0e380595dab7720e6b4a9f8f19c5947b90e84fa23b7cedea945222e/PyGithub-1.34.tar.gz
Collecting aiohttp<3.4.0,>=3.3.0 (from discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/72/6a/5bbf3544fe8de525f4521506b372dc9c3b13070fe34e911c976aa95631d7/aiohttp-3.3.2.tar.gz
  Installing build dependencies ... done
Collecting websockets<6.0,>=5.0 (from discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4b/c6/026da2eeed75a49dd0b72a0c7ed6ee5cb2943e396ca9753eabff7359b27b/websockets-5.0.1.tar.gz
Collecting gitdb2>=2.0.0 (from GitPython==2.1.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/a9/fb/d3afc4e2a8d506a07af19f125f7a473ae1b56f942ed2ba80776eb8ae23b1/gitdb2-2.0.4-py2.py3-none-any.whl
Collecting olefile (from Pillow==4.2.1->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/d3/8a/e0f0e56d6a542dd987f9290ef7b5164636ee597ce8c2932c19c78292d5ec/olefile-0.45.1.zip
Collecting pyjwt (from PyGithub==1.34->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/93/d1/3378cc8184a6524dc92993090ee8b4c03847c567e298305d6cf86987e005/PyJWT-1.6.4-py2.py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/9d/b9/3cf1b908d7af6530209a7a16d71ab2734a736c3cdf0657e3a06d0209811e/multidict-4.3.1.tar.gz
Collecting async_timeout<4.0,>=3.0 (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/96/0f/e6357458c87fb4ed8f3df215773f3caad40968f10e05552cbd8bd28415e4/async_timeout-3.0.0-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/43/b8/057c3e5b546ff4b24263164ecda13f6962d85c9dc477fcc0bcdcb3adb658/yarl-1.2.6.tar.gz
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython==2.1.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/0f/14/e3112808b727f72df9531fc2f00b84d4966e66001748b6883a21c767e902/smmap2-2.0.4-py2.py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py==1.0.0a1477+g184c430->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: lxml, psutil, smmap2, gitdb2, GitPython, olefile, Pillow, pyfiglet, attrs, chardet, multidict, async-timeout, idna, yarl, aiohttp, tokage, pytz, pyjwt, PyGithub, websockets, discord.py
  Running setup.py install for lxml ... error
    Complete output from command C:\Users\amonp\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\amonp\\AppData\\Local\\Temp\\pip-install-qe5ggklp\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\amonp\AppData\Local\Temp\pip-record-h3a3z65k\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Building lxml version 3.8.0.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\lxml
    copying src\lxml\builder.py -> build\lib.win32-3.7\lxml
    copying src\lxml\cssselect.py -> build\lib.win32-3.7\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win32-3.7\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win32-3.7\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win32-3.7\lxml
    copying src\lxml\sax.py -> build\lib.win32-3.7\lxml
    copying src\lxml\usedoctest.py -> build\lib.win32-3.7\lxml
    copying src\lxml\_elementpath.py -> build\lib.win32-3.7\lxml
    copying src\lxml\__init__.py -> build\lib.win32-3.7\lxml
    creating build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win32-3.7\lxml\includes
    creating build\lib.win32-3.7\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win32-3.7\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win32-3.7\lxml\html
    creating build\lib.win32-3.7\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win32-3.7\lxml\isoschematron
    copying src\lxml\lxml.etree.h -> build\lib.win32-3.7\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win32-3.7\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win32-3.7\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win32-3.7\lxml\includes
    creating build\lib.win32-3.7\lxml\isoschematron\resources
    creating build\lib.win32-3.7\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win32-3.7\lxml\isoschematron\resources\rng
    creating build\lib.win32-3.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl
    creating build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-3.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    creating build\temp.win32-3.7\Release\src\lxml
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc\lxml\includes -IC:\Users\amonp\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\amonp\AppData\Local\Programs\Python\Python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win32-3.7\Release\src\lxml\lxml.etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    lxml.etree.c
    src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    creating Users
    creating Users\amonp
    creating Users\amonp\AppData
    creating Users\amonp\AppData\Local
    creating Users\amonp\AppData\Local\Temp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /TcC:\Users\amonp\AppData\Local\Temp\xmlXPathInit15x_6rok.c /FoUsers\amonp\AppData\Local\Temp\xmlXPathInit15x_6rok.obj
    xmlXPathInit15x_6rok.c
    C:\Users\amonp\AppData\Local\Temp\xmlXPathInit15x_6rok.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\amonp\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\amonp\\AppData\\Local\\Temp\\pip-install-qe5ggklp\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\amonp\AppData\Local\Temp\pip-record-h3a3z65k\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\amonp\AppData\Local\Temp\pip-install-qe5ggklp\lxml\
Requirements installation failed. Perhaps some dependency is missing or access was denied? Possible solutions:
- Run as administrator
- Google the error
- Visit the Discord server for help
Press any key to exit.

**Comment by MrZeroLord** [comment]
ehm yo could u maybe tell me the solution?
i got also some problems with installing lxml
