### ISSUE TITLE
Issue:what is this

### ISSUE THREAD

**Issue by Rainerss** [appu1232/Discord-Selfbot#400]
it loads for 10 minutes then it says this

'unclosed client session' and 'unclosed connector' are not errors
--------------------------
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000000CFCF78BBE0>

**Comment by LyricLy** [comment]
You appear to have solved your own issue. It tells you that "unclosed client session" is not an error, and then says "unclosed client session".
