### ISSUE TITLE
i get this after running "run.bat" 

### ISSUE THREAD

**Issue by Soheab** [appu1232/Discord-Selfbot#401]
![image](https://user-images.githubusercontent.com/33902984/45501169-c8f50d80-b780-11e8-878b-87e0a09ffae2.png)

**Comment by Soheab** [comment]
now this 
![image](https://user-images.githubusercontent.com/33902984/45503475-35730b00-b787-11e8-9d06-b68123def018.png)

**Comment by Macley-Kun** [comment]
Solved. Should be closed.
Also watch out, Heroku got a new stack (18) and some python versions aren't supported anymore.
Fix is using this in where you put all the files and stuff:
[runtime.txt](https://github.com/appu1232/Discord-Selfbot/files/2380398/runtime.txt)
Also who changed the Procfile? That doesn't work haha, you need to use this Procfile b/c it isn't bash. It's ran by python!
https://www.filemail.com/d/nblcinjomyuftlc
Really suggest changing that.

**Comment by Soheab** [comment]
wdym?

**Comment by Soheab** [comment]
> Solved. Should be closed.
> Also watch out, Heroku got a new stack (18) and some python versions aren't supported anymore.
> Fix is using this in where you put all the files and stuff:
> [runtime.txt](https://github.com/appu1232/Discord-Selfbot/files/2380398/runtime.txt)
> Also who changed the Procfile? That doesn't work haha, you need to use this Procfile b/c it isn't bash. It's ran by python!
> https://www.filemail.com/d/nblcinjomyuftlc
> Really suggest changing that.

wdym?

**Comment by Macley-Kun** [comment]
Dude i legit just helped you getting this to work. You saw with your own eyes that it didn't worked the procfile. Also buildling didn't work ether due to the new stack config.
Also you can hit close.

**Comment by Soheab** [comment]
> Dude i legit just helped you getting this to work. You saw with your own eyes that it didn't worked the procfile. Also buildling didn't work ether due to the new stack config.
> Also you can hit close.

sry.. but what is a procfile and what must i do with it?

**Comment by Macley-Kun** [comment]
We just had it working? Why did you put the runtime everywhere???? I never said you had to do that, not even ever saying you had to put it everywhere?????

**Comment by Soheab** [comment]
i didnt put it in all the files look.. this are all the bots files rn
![image](https://user-images.githubusercontent.com/33902984/45508280-b1278480-b794-11e8-8291-154fe0c3b8cb.png)

**Comment by Soheab** [comment]
so if i start run.bat it finishes with this... ![image](https://user-images.githubusercontent.com/33902984/45508873-5131dd80-b796-11e8-8e8c-ce107614ffbb.png)

**Comment by Macley-Kun** [comment]
Seems that i've mistaken who you are, wierd that you didn't react on this part differently:
```
Dude i legit just helped you getting this to work. You saw with your own eyes that it didn't worked the procfile. Also buildling didn't work ether due to the new stack config.
Also you can hit close.
```
No clue what your doing there, but what is visual studio stuff doing there? Give more context.

**Comment by Soheab** [comment]
idk what visual studio is doing it said i should download it first so i did lol

**Comment by Macley-Kun** [comment]
recheck the steps here in the wiki. No where it would ever even mention vs.

**Comment by Soheab** [comment]
> recheck the steps here in the wiki. No where it would ever even mention vs.

Look at the first screenshot it said ‘error: Microsoft visual c++ is required’

**Comment by MyriaCore** [comment]
Bump. I've got this exact issue.

**Comment by MyriaCore** [comment]
I think it has to do with the way its downloading and installing the requirements. It failed during the lxml setup, so I pip installed it outside of the script, hoping it'd resolve itself and continue, but it got caught on the same one. I removed it from requirements, then it got caught on another dep. I'm currently trying to manually install all the deps and remove them from the requirements, I'll post what happens.

**Comment by MyriaCore** [comment]
OK so it didn't work, but I learned a few valuable things from it.

I'm still 95% sure that the script failed b/c of how it was installing things. It would always fail during the setup of a specific dependency, and it would never get past the line `python -m pip install --user -r requirements.txt` in the batch file.

I ended up [editing the requirements.txt](https://gist.github.com/MyriaCore/831d30fe8878597ec5ba59ed56a6d380) such that I didn't explicitly add the version numbers, _and it went through perfectly_. It ended up throwing mountains and mountains of errors and being generally unusable, but regardless, what that proved was that the failure was b/c of how it was trying to setup the deps in the original requirements.txt. 

Obviously this doesn't rly fix anything, since it seems as though there are facilities being used in this repo that break when you download newer / recommended versions of the requirements. I wanna say the fix is to try to get this on new deps, but it could easily be b/c I'm doing something astonishingly idiotic, and nobody else has this problem.

**Comment by Soheab** [comment]
> OK so it didn't work, but I learned a few valuable things from it.
> 
> I'm still 95% sure that the script failed b/c of how it was installing things. It would always fail during the setup of a specific dependency, and it would never get past the line `python -m pip install --user -r requirements.txt` in the batch file.
> 
> I ended up [editing the requirements.txt](https://gist.github.com/MyriaCore/831d30fe8878597ec5ba59ed56a6d380) such that I didn't explicitly add the version numbers, _and it went through perfectly_. It ended up throwing mountains and mountains of errors and being generally unusable, but regardless, what that proved was that the failure was b/c of how it was trying to setup the deps in the original requirements.txt.
> 
> Obviously this doesn't rly fix anything, since it seems as though there are facilities being used in this repo that break when you download newer / recommended versions of the requirements. I wanna say the fix is to try to get this on new deps, but it could easily be b/c I'm doing something astonishingly idiotic, and nobody else has this problem.

ah okay hmmm i removed the versions in requirements so the bot installed but now it doesnt start it just repeatly says that on pic
![image](https://user-images.githubusercontent.com/33902984/45643777-24decf80-babc-11e8-8f15-004c44f95807.png)
