### ISSUE TITLE
Import name fails & unclosed client session

### ISSUE THREAD

**Issue by NitroPlayz** [appu1232/Discord-Selfbot#402]
When i start run.bat i get these issues:
![issue](https://user-images.githubusercontent.com/42419023/45585836-a7fcfb80-b8eb-11e8-8876-e08727215e3f.PNG)

**Comment by cook1e0** [comment]
I keep getting the "unclosed client session" error too, which keeps restarting the bot right after it logged in

**Comment by LyricLy** [comment]
"unclosed client session" is not an error, as it says immediately above it on startup. It is either a symptom of an actual error or not an issue at all. As for the actual errors, it seems as though your bot is outdated.

**Comment by Ayudon** [comment]
I kept getting this error even _after_ updating, and even still after deleting and reinstalling the bot, and this keeps happening to me still:
![screenshot_955](https://user-images.githubusercontent.com/43678524/46215597-cb706f00-c30b-11e8-9367-037731b5f153.png)
After a while, the error keeps looping, and all this happens even though all requirements have been satisfied.

**Comment by LyricLy** [comment]
"'unclosed client session' is not an error" is included in your screenshot. There is nothing I can do to help you with only this.

**Comment by Eternal-Scripts** [comment]
Same here, unclosed client session and when i try talk with my self-bot, he don't answer...
but he's online.

**Comment by MathiasTopKek** [comment]
The error is caused cause discord declines the token and throws an authorization error for some strange error i had to find it out the hard way. That's why appu is probably not answering you, anyways i hope he finds a fix for it.

**Comment by LyricLy** [comment]
There is no authorization error in this screenshot.

**Comment by MathiasTopKek** [comment]
@LyricLy here is the full error and i used another bot that throw the same error but it had debug mode and it showed that it was cause discord api was throwing authorization decline.
![kx1](https://user-images.githubusercontent.com/44008063/46906153-b39e0b00-cf07-11e8-8e3a-7e6a8ba22e71.png)

**Comment by LyricLy** [comment]
Let me repeat this. As it says inside the screenshots you are sending, `Unclosed client session` and `Unclosed connector` messages *are not errors*. If your bot is not responding, it is due to something unrelated and I am unable to provide assistance with only these screenshots.
