### ISSUE TITLE
Selfbot installing error

### ISSUE THREAD

**Issue by xyn-n** [appu1232/Discord-Selfbot#409]
https://i.imgur.com/hVRXldg.png

I'm currently receiving this error after attempting to download the selfbot on a new PC. Any clue as to why? ;w;

**Comment by LyricLy** [comment]
The selfbot supports versions 3.5.3-3.6.6.

**Comment by xyn-n** [comment]
Oh, I installed the wrong version of Python. Whoops.

**Comment by Macley-Kun** [comment]
@xyn-n you can close the issue if it's resoveld 😉
