### ISSUE TITLE
Can't start up bot anymore

### ISSUE THREAD

**Issue by xeniusw** [appu1232/Discord-Selfbot#422]
[Screenshot](http://cowhook.win/i/by18ft.png)

Help please?

**Comment by LyricLy** [comment]
The bot seems to have loaded normally.

**Comment by jacobcxdev** [comment]
I'm having issues still - my bot hasn't been able to start for 12 days! Are you able to help me with setting it up?

**Comment by mouselifter** [comment]
Same as jacob
