### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by xbkotz** [appu1232/Discord-Selfbot#423]
Won't install upon the first install. 
https://i.imgur.com/bxT7Smr.png

**Comment by Rerd** [comment]
In the README file is says:
`### IMPORTANT: **If you are running into [this issue](https://i.imgur.com/h9naJ77.png) with starting the bot, please uninstall Python version 3.5.2 and install [3.5.3 or higher](https://www.python.org/downloads/release/python-365/). Make sure you check "add to PATH" on install.**`
