### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by KuroSenseii** [appu1232/Discord-Selfbot#426]
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 115.69.164.101:8080 ssl:None [Connect call failed ('115.69.164.101', 8080)]

a lot of command dont work anymore with this error :\

**Comment by overgdbg** [comment]
Have same problem.

**Comment by KuroSenseii** [comment]
ok i have found a temp fix.

Go to your Config.json file and turn "track" to false

this is this cogs *track( having problem with the url
