### ISSUE TITLE
Something went wrong: WebSocket connection is closed

### ISSUE THREAD

**Issue by tooruu** [appu1232/Discord-Selfbot#432]
![image](https://user-images.githubusercontent.com/40900803/49909313-f8eaa480-fe86-11e8-84ab-f6154224ef2b.png)

**Comment by KingKunsama** [comment]
Yes, I am having the same issue as you, this needs a fix

**Comment by DexStarrUnderscore** [comment]
me too

**Comment by Soheab** [comment]
same

**Comment by chenzw95** [comment]
This is not a bug with the bot itself.
