### ISSUE TITLE
Just a pain in the butt (running parrotos)

### ISSUE THREAD

**Issue by swagskillsup** [appu1232/Discord-Selfbot#434]
`┌─[user@parrot]─[~/Desktop/Discord-Selfbot]
└──╼ $bash run_linuxmac.sh 

Starting auto-update
Fetching origin
From https://github.com/appu1232/Discord-Selfbot
 //* branch            master     -> FETCH_HEAD
The bot is up to date.
Checking requirements...
Using pip as a python3 module
Upgrading requirements
/usr/bin/python3: No module named pip
Requirements installation failed`
+ something is wrong :disappointed:

**Comment by marknl** [comment]
Run:
sudo /usr/bin/python3 -m ensurepip --default-pip

Then try again.
