### ISSUE TITLE
how can i change the python version it runs it with?

### ISSUE THREAD

**Issue by Soheab** [appu1232/Discord-Selfbot#443]
i think if i double click on the run.bat thing it opens it with python 3.7 and that is not supported so how can i let it open with python 3.6? i have them both installed

**Comment by ALobsterDog** [comment]
you can just run selfloop.py from the cmd prompt using the specific executable from the python version you want.

open the terminal in your /selfbot/ directory and enter:

    C:\PYTHON\FILEPATH\python36\python.exe selfloop.py

you will need to make sure you have all the bots dependencies where it can see them, so you may need to reinstall discord.py by running pip with python36

**Comment by chenzw95** [comment]
This is not a support forum.
