### ISSUE TITLE
[Feature Request][Cog] Command to mass move users in voice channels

### ISSUE THREAD

**Issue by Bluscream** [appu1232/Discord-Selfbot#49]
Coming from Teamspeak this almost feels essential (https://www.myteamspeak.com/addons/a5a52764-94b2-4ef2-8bf9-93eae3b0f523)

Vortex has such a feature for example: https://github.com/jagrosh/Vortex/blob/master/src/vortex/commands/MagnetCmd.java#L100

**Comment by LyricLy** [comment]
Clearing out dead issues.
