### ISSUE TITLE
[Feature Request] Dynamic help texts to have to have the correct bot prefix everywhere

### ISSUE THREAD

**Issue by Bluscream** [appu1232/Discord-Selfbot#52]
Currently the bot prefix is very static in most of the help messages and other. Maybe make a small helper function like
```py
def parse_prefix(text):
    cfg = load_config()
    return text.replace("{p}", cfg["bot_prefix"])
```
and use that whenever possible just to get the prefix right :D

**Comment by Bluscream** [comment]
For example in the help texts the prefix is wrong almost all the time:
![image](https://user-images.githubusercontent.com/3318223/27758504-8ef16810-5e15-11e7-912e-22f35047ff47.png)

**Comment by chenzw95** [comment]
Just a note for future reference: the help command is handled internally by discord.py, which reads off the docstring. The class of interest here is HelpFormatter, and we will probably need to override the `format` method.

**Comment by Bluscream** [comment]
The helper function does now exist on the config-manager branch for which i will try to adjust all the non-docstring strings to use it but yeah im sure we have to find a way to set the docstring for commands via codw
