### ISSUE TITLE
[Feature Request] channelinfo command

### ISSUE THREAD

**Issue by Bluscream** [appu1232/Discord-Selfbot#53]
There is userinfo and serverinfo but no channelinfo :(

![spectra's channelinfo](https://cdn.discordapp.com/attachments/299294015033966592/329247610147962881/Screenshot_20170627-151147.jpg)

**Comment by Jan200101** [comment]
I have that.
![image](https://user-images.githubusercontent.com/15076013/27761434-1105fb18-5e5c-11e7-9540-45d7ac2a4a32.png)
I'm gonna make some changes to it and propose it

**Comment by Bluscream** [comment]
Awesome, thank you ♥

**Comment by Jan200101** [comment]
Incase you are still interested
here is a link to the raw [channelinfo cog](https://raw.githubusercontent.com/Jan200101/Appu-cogs/master/channelinfo/channelinfo.py)
