### ISSUE TITLE
Mac OS error

### ISSUE THREAD

**Issue by XCalibruh** [appu1232/Discord-Selfbot#8]
when i run "python loopself.py" into the cmd on MacOS sierra in the terminal in the folder after installing "pip -r install requirements.txt" i get this in the terminal. it just repeats for ever. Your bot is very good and i am looking forward to using after this silly error goes away. I have modified config.json and everything else and installed python for mac os. anything would help ;)
<img width="566" alt="screen shot 2017-04-05 at 9 24 32 pm" src="https://cloud.githubusercontent.com/assets/20650625/24703422/8715301c-1a46-11e7-822b-1388dfb24e92.png">

**Comment by appu1232** [comment]
It seems that the installation of requirements.txt did not work correctly, It's actually ``pip install -r requirements.txt`` not ``pip -r install requirements.txt``. I'm not sure if you just mistyped it now or not but try it again as ``pip install -r requirements.txt`` if you don't mind.

**Comment by appu1232** [comment]
I'm assuming this worked for you so I'm closing this issue. Please reopen if your issue persists.

**Comment by XCalibruh** [comment]
Ya it worked, sorry for the late reply! :)

**Comment by XCalibruh** [comment]
Still not working ;( 
<img width="565" alt="screen shot 2017-04-07 at 5 23 20 pm" src="https://cloud.githubusercontent.com/assets/20650625/24789560/f7a638be-1bb6-11e7-93c7-ce28b404c10b.png">
