### ISSUE TITLE
Mac OS error pt 2

### ISSUE THREAD

**Issue by XCalibruh** [appu1232/Discord-Selfbot#9]
Reinstalled the requirements and assumed i had mistyped it but unfortunately didn't work (i even copied and pasted it) Any help would be appreciated :) 
<img width="565" alt="screen shot 2017-04-07 at 5 23 20 pm" src="https://cloud.githubusercontent.com/assets/20650625/24789716/78394d90-1bb7-11e7-81bc-927d90f31f3a.png">

**Comment by XCalibruh** [comment]
i even reinstalled python and everything (even discord!)

**Comment by appu1232** [comment]
Hi, run the ``pip install -r requirements.txt`` again and post a screenshot of the output when you do that. Also, join the Discord https://discord.gg/TBQE72k where I can help more extensively (I'll post the solution here after we figure it out for anyone else that may come across this in the future). I'll be on later today to help.

**Comment by XCalibruh** [comment]
Ok ty
