### ISSUE TITLE
Run hidden on startup (how to)

### ISSUE THREAD

**Issue by Benji-13** [appu1232/Discord-Selfbot#99]
One way to run the bot on startup without seeing cmd it to convert run.bat to an exe then include a .vbs file that when ran, it starts run.exe as a hidden program.

Link to .exe - https://github.com/Benji-13/Selfbotfiles/blob/master/run.exe

Link to .vbs - https://github.com/Benji-13/Selfbotfiles/blob/master/runhidden.vbs

**Comment by appu1232** [comment]
Noted. Although I'm hesitant making the exe the primary way of running the bot since I'm sure many may be uncomfortable running an exe file vs a bat file that you can at least see the contents of easily. I'll probably add this as an option in the instructions to run hidden but also give the option to use run.bat.

**Comment by Benji-13** [comment]
You would also need to instruct users to run the .exe to complete the set up then copy the .vbs (or a shortcut of it) to the startup folder.

**Comment by LyricLy** [comment]
I created a quick program to simplify the process: https://github.com/LyricLy/File-Uploads/blob/master/runhidden.exe
This one simply starts run.bat in a hidden command line window, without the need for a separate .vbs file.

**Comment by Benji-13** [comment]
LyricLy that would be good but you still need to be able to run the program in a visible window for the initial setup.

**Comment by LyricLy** [comment]
Yeah, that's unavoidable, really.

**Comment by Dunciboy** [comment]
Additionally you could for example use http://nssm.cc/usage to run the bat file as a service.
